// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrdkxjnkogzawtsmqcsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyZGt4am5rb2d6YXd0c21xY3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODcyNjAsImV4cCI6MjA3MTA2MzI2MH0.nW2j96Oj2wBuWn9Yxx7bncs_aLqg9O6_JnQD98nWDdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});